### ISSUE TITLE
v1.3.1: Reply to producer is not working

### ISSUE THREAD

**Issue by giminni** [Gippsman2017/node-red-contrib-redlink#8]
Starting with V1.3.1 producer in send-only mode is working with two consumers with same service running from three different docker containers.

But testing a consumer with default parameters does not work.

I guess that the  consumer is not resetting the notify counter after read and/or the producer does not get the reply message back from the consumer.

**Comment by Gippsman2017** [comment]
Thanks for testing this giminni, confirmed, I had an incorrect notify query set, fixed in V 1.3.2
Use this flow to test

[{"id":"b2808139.ecd5c","type":"tab","label":"V1.3.2 Test","disabled":false,"info":""},{"id":"c6a73ea4.736178","type":"redlink store","z":"b2808139.ecd5c","listenAddress":"localhost","listenPort":"3100","southInsert":true,"peerAddress":"0.0.0.0","peerPort":443,"headers":[{"ip":"localhost","port":"3101"},{"ip":"localhost","port":"3102"}],"name":"qwerty","meshName":"mesh0","oldStore":true,"showRegistration":true,"showDebug":true,"outputs":3,"isUserCertificate":false,"userKey":"","userCertificate":"","x":450,"y":100,"wires":[["293f528.f9602ae"],["4e046df5.d73a64"],["d7342904.427b18"]]},{"id":"a509bdc7.87279","type":"redlink producer","z":"b2808139.ecd5c","name":"MyProducer","producerStoreName":"mesh0:qwerty","producerConsumer":"A","producerTTL":15,"producerETT":300,"priority":0,"timeout":-1,"sendOnly":false,"manualRead":false,"rateTypeSendReceive":"none","rateSendReceive":1,"rateUnitsSendReceive":"second","nbRateUnitsSendReceive":"","topic":"","cmd":"send","private":false,"ttl":null,"tba":null,"showDebug":false,"outputs":3,"notifyInterval":15,"x":360,"y":520,"wires":[["69203a59.95e66c"],["660199c7.ba42b"],["9fdd43cd.71d15"]]},{"id":"8f39946c.033fe8","type":"redlink consumer","z":"b2808139.ecd5c","name":"A","consumerStoreName":"mesh0:qwerty2","intransit":"1","manualReadReceiveSend":false,"rateTypeReceiveSend":"none","rateReceiveSend":1,"rateUnitsReceiveSend":"second","nbRateUnitsReceiveSend":"1","topicReceiveSend":"","cmd":"read","showStatsReceiveSend":false,"statsFrequencyReceiveSend":0,"showDebugReceiveSend":false,"outputs":3,"x":630,"y":640,"wires":[["2986ae4e.20a522","565a1fea.22eef8"],["bb1340af.706e7"],["d58dec05.94b8e8"]]},{"id":"b35acbfe.9396a","type":"inject","z":"b2808139.ecd5c","name":"SingleShot","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":420,"wires":[["a509bdc7.87279"]]},{"id":"293f528.f9602ae","type":"debug","z":"b2808139.ecd5c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":610,"y":80,"wires":[]},{"id":"4e046df5.d73a64","type":"debug","z":"b2808139.ecd5c","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":610,"y":120,"wires":[]},{"id":"d7342904.427b18","type":"debug","z":"b2808139.ecd5c","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":610,"y":160,"wires":[]},{"id":"2986ae4e.20a522","type":"debug","z":"b2808139.ecd5c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":810,"y":580,"wires":[]},{"id":"bb1340af.706e7","type":"debug","z":"b2808139.ecd5c","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":810,"y":620,"wires":[]},{"id":"d58dec05.94b8e8","type":"debug","z":"b2808139.ecd5c","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":810,"y":660,"wires":[]},{"id":"69203a59.95e66c","type":"debug","z":"b2808139.ecd5c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":610,"y":480,"wires":[]},{"id":"e7a78be.aa51d78","type":"inject","z":"b2808139.ecd5c","name":"","topic":"listRegistrations","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":280,"y":80,"wires":[["c6a73ea4.736178"]]},{"id":"c5f3d8cb.212518","type":"inject","z":"b2808139.ecd5c","name":"","topic":"listStore","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":269,"y":118,"wires":[["c6a73ea4.736178"]]},{"id":"159fed99.6b3dea","type":"inject","z":"b2808139.ecd5c","name":"","topic":"flushStore","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":270,"y":160,"wires":[["c6a73ea4.736178"]]},{"id":"4f1e0032.c8613","type":"inject","z":"b2808139.ecd5c","name":"ManualRead","topic":"read","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":450,"y":640,"wires":[["8f39946c.033fe8"]]},{"id":"565a1fea.22eef8","type":"function","z":"b2808139.ecd5c","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"x":630,"y":580,"wires":[["8f39946c.033fe8"]]},{"id":"9e0da78b.e9772","type":"inject","z":"b2808139.ecd5c","name":"ManualRead","topic":"read","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":540,"wires":[["a509bdc7.87279"]]},{"id":"3cc60928.95b78e","type":"redlink store","z":"b2808139.ecd5c","listenAddress":"localhost","listenPort":"3101","southInsert":true,"peerAddress":"0.0.0.0","peerPort":443,"headers":[],"name":"qwerty2","meshName":"mesh0","oldStore":true,"showRegistration":true,"showDebug":true,"outputs":3,"isUserCertificate":false,"userKey":"","userCertificate":"","x":620,"y":280,"wires":[["5e17ff28.87eaa8"],["8d7c3cb2.f42708"],["b9218225.42cf18"]]},{"id":"5e17ff28.87eaa8","type":"debug","z":"b2808139.ecd5c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":770,"y":240,"wires":[]},{"id":"8d7c3cb2.f42708","type":"debug","z":"b2808139.ecd5c","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":771,"y":281.5,"wires":[]},{"id":"b9218225.42cf18","type":"debug","z":"b2808139.ecd5c","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":770,"y":320,"wires":[]},{"id":"53f466a3.33f84","type":"inject","z":"b2808139.ecd5c","name":"","topic":"listRegistrations","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":440,"y":240,"wires":[["3cc60928.95b78e"]]},{"id":"68a5cf91.63b98","type":"inject","z":"b2808139.ecd5c","name":"","topic":"listStore","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":420,"y":280,"wires":[["3cc60928.95b78e"]]},{"id":"49cd474.fb130b8","type":"inject","z":"b2808139.ecd5c","name":"","topic":"flushStore","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":420,"y":320,"wires":[["3cc60928.95b78e"]]},{"id":"9625294b.ed3948","type":"redlink store","z":"b2808139.ecd5c","listenAddress":"localhost","listenPort":"3102","southInsert":true,"peerAddress":"0.0.0.0","peerPort":443,"headers":[],"name":"qwerty3","meshName":"mesh0","oldStore":true,"showRegistration":true,"showDebug":true,"outputs":3,"isUserCertificate":false,"userKey":"","userCertificate":"","x":600,"y":400,"wires":[["ac3b1c24.288e"],["ba834f1c.686478"],["1eae38fc.ff375f"]]},{"id":"ac3b1c24.288e","type":"debug","z":"b2808139.ecd5c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":750,"y":360,"wires":[]},{"id":"ba834f1c.686478","type":"debug","z":"b2808139.ecd5c","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":751,"y":401.5,"wires":[]},{"id":"1eae38fc.ff375f","type":"debug","z":"b2808139.ecd5c","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":750,"y":440,"wires":[]},{"id":"17dbe656.4e123a","type":"inject","z":"b2808139.ecd5c","name":"","topic":"listRegistrations","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":420,"y":360,"wires":[["9625294b.ed3948"]]},{"id":"7bbf731c.b6d2dc","type":"inject","z":"b2808139.ecd5c","name":"","topic":"listStore","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":400,"y":400,"wires":[["9625294b.ed3948"]]},{"id":"2d51e435.1d01fc","type":"inject","z":"b2808139.ecd5c","name":"","topic":"flushStore","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":400,"y":440,"wires":[["9625294b.ed3948"]]},{"id":"19a30507.4df723","type":"redlink consumer","z":"b2808139.ecd5c","name":"A","consumerStoreName":"mesh0:qwerty3","intransit":"1","manualReadReceiveSend":false,"rateTypeReceiveSend":"none","rateReceiveSend":1,"rateUnitsReceiveSend":"second","nbRateUnitsReceiveSend":"","topicReceiveSend":"","cmd":"read","showStatsReceiveSend":false,"statsFrequencyReceiveSend":0,"showDebugReceiveSend":false,"outputs":3,"x":610,"y":760,"wires":[["802ca924.1376c8","d8230db5.25a738"],["e717c0b9.fc154"],["d6bb4abf.5f506"]]},{"id":"802ca924.1376c8","type":"debug","z":"b2808139.ecd5c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":790,"y":700,"wires":[]},{"id":"e717c0b9.fc154","type":"debug","z":"b2808139.ecd5c","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":790,"y":740,"wires":[]},{"id":"d6bb4abf.5f506","type":"debug","z":"b2808139.ecd5c","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":790,"y":780,"wires":[]},{"id":"4e62da98.aeb8cc","type":"inject","z":"b2808139.ecd5c","name":"ManualRead","topic":"read","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":430,"y":760,"wires":[["19a30507.4df723"]]},{"id":"d8230db5.25a738","type":"function","z":"b2808139.ecd5c","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"x":590,"y":700,"wires":[["19a30507.4df723"]]},{"id":"71afcdd9.1d7b6c","type":"trigger","z":"b2808139.ecd5c","op1":"1","op2":"0","op1type":"str","op2type":"str","duration":"-100","extend":false,"units":"ms","reset":"","bytopic":"all","name":"","x":140,"y":360,"wires":[["a509bdc7.87279"]]},{"id":"9fdd43cd.71d15","type":"debug","z":"b2808139.ecd5c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":610,"y":540,"wires":[]},{"id":"660199c7.ba42b","type":"debug","z":"b2808139.ecd5c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":770,"y":500,"wires":[]},{"id":"ca196719.ce35e8","type":"inject","z":"b2808139.ecd5c","name":"MultipleShot","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":280,"wires":[["71afcdd9.1d7b6c"]]}]
